import json

from openai import OpenAI

from app.core.config import settings
from app.core.tracing import get_tracer


class LlmSummarizationService:
    def __init__(self):
        if not settings.openai_api_key:
            raise ValueError("OPENAI_API_KEY is required when LLM compaction is enabled")

        self.client = OpenAI(api_key=settings.openai_api_key)
        self.tracer = get_tracer("llm-summarization-service")

    def _build_prompt(self, memories: list) -> str:
        serialized_memories = []

        for idx, memory in enumerate(memories, start=1):
            serialized_memories.append(
                {
                    "index": idx,
                    "memory_id": str(memory.memory_id),
                    "title": memory.title,
                    "memory_type": memory.memory_type,
                    "scope": memory.scope,
                    "tenant_id": memory.tenant_id,
                    "tags": memory.tags,
                    "summary": memory.summary,
                    "content": memory.content,
                }
            )

        return f"""
You are summarizing multiple agent memory records into one consolidated memory.

Your goal:
- identify the recurring signal across the memories
- remove redundancy
- preserve the most important facts
- produce a clean title, summary, and content for a compacted memory record

Return ONLY valid JSON with this exact schema:
{{
  "title": "string",
  "summary": "string",
  "content": "string"
}}

Rules:
- Title must be concise and reusable.
- Summary must be short but informative.
- Content must be structured, readable, and useful for future retrieval.
- Do not mention that this was generated by an AI.
- Do not include markdown code fences.

Source memories:
{json.dumps(serialized_memories, ensure_ascii=False, indent=2)}
""".strip()

    def summarize_memories(self, memories: list) -> dict:
        with self.tracer.start_as_current_span("llm.compaction.summarize") as span:
            prompt = self._build_prompt(memories)

            span.set_attribute("llm.memory_count", len(memories))
            span.set_attribute("llm.model", settings.openai_chat_model)

            response = self.client.chat.completions.create(
                model=settings.openai_chat_model,
                messages=[
                    {
                        "role": "system",
                        "content": "You are a precise backend memory compaction assistant. Return only valid JSON.",
                    },
                    {
                        "role": "user",
                        "content": prompt,
                    },
                ],
                temperature=0.2,
            )

            text = response.choices[0].message.content.strip()
            span.set_attribute("llm.response_length", len(text))

            try:
                data = json.loads(text)
                span.set_attribute("llm.parse_success", True)

                return {
                    "title": data["title"].strip(),
                    "summary": data["summary"].strip(),
                    "content": data["content"].strip(),
                }
            except Exception:
                span.set_attribute("llm.parse_success", False)

                return {
                    "title": "Compacted memory",
                    "summary": "LLM summarization fallback summary",
                    "content": text[:5000],
                }